name: Conda Pillow

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  conda:    
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          channels: defaults
      - name: Conda info
        run: conda info
      - name: Install Pillow
        run: conda install pillow=9.0.1 jpeg=9e
      - name: Check libjepg.dll
        run: ls -l C:\Miniconda\envs\test\Library\bin\libjpeg.dll
      # - name: Dependencies libjepg.dll
      #   run: |
      #     Invoke-WebRequest https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip -OutFile Dependencies.zip
      #     Expand-Archive Dependencies.zip
      #     Dependencies\Dependencies.exe -chain C:\Miniconda\envs\test\Library\bin\libjpeg.dll
      - name: Import Pillow
        run: python -c 'from PIL import Image'
